name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployUAT:
    name: Deploy to UAT 
   # if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: UAT
      url: 'http://development.app.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  DeployDevelopment:
    name: Deploy to Development 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: UAT
      url: 'http://test.app.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.production.app.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
