name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ sample}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref }}
            ghcr.io/${{ github.repository }}:latest

     # - name: Compile
       # run: echo Hello, world!
    
  DeployUAT:
    name: Deploy to UAT 
   # if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: UAT
      url: 'http://uat.app.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  DeployDevelopment:
    name: Deploy to Development 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://development.app.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.production.app.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
